spring.datasource.url=jdbc:mysql://localhost:3307/fyp
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

minio.url=http://localhost:9000
minio.access.key=minioadmin
minio.secret.key=minioadmin
minio.bucket=fyp-bucket

web3.rpc.url=http://127.0.0.1:8545
web3.contract.address=PUT_YOUR_CONTRACT_HERE
web3.private.key=SET_IN_ENVIRONMENT_VARIABLE
